### ISSUE TITLE
Define NPC data and sheets

### ISSUE THREAD

**Issue by Spice-King** [Spice-King/foundry-swnr#13]
# NPC data
## Combat stuff
- Moral Score: 1-12 (as seen in book, 6-12)
- Morale check: 2d6 > morale score is a failure, which means a score of 12 can't fail, Warpaint has +1 bonus to score
- Hit Dice: 1d8 per die for HP
- AC: plus same type as PCs, (powered, combat, normal, primitive)
- Attack bonus: often the same as HD, might be higher, some times two attacks, gengineered murder beast has 4 attacks
- Damage: unarmed/weapon, might have extra damage, bots and beasts have dies for damage
- Movement: 10m is standard
- Skills: bonus for skills for their profession, not used for the rest
- Saves: flat, typically 15 - half HD, round down
- Psychics: 1/3 HD, rounded up for effort
- Special traits: foci
## Social stuff
- Faction affiliation
- Homeworld
- Disposition/reaction roll
- Goals
- Notes/Bio
# Sheets
- Split combat and social into two sheets?
- Third option with both?
- Do one, but make the sections toggle visablity?

**Comment by BrightStarsBeard** [comment]
I am very excited about this! I am currently running a SWN game on Fantasy Grounds with something cobbled together in moreCore.  I have a very limited coding skill set but please let me know if I can help! Do you have any sense of when NPC sheets might be supported?  Thanks for all your work.
