### ISSUE TITLE
Every update wiping data from character sheets.

### ISSUE THREAD

**Issue by detraya** [Spice-King/foundry-swnr#14]
After the last two updates you've published all biographical information has gone missing from character sheets, including class, species/gender, homeworld, background, employer, and everything in the biography.  I've been able to recover it by pulling an old version of the actors.db and copying the data over. 

notably, nonbiographical information, such as hp, xp, ac, and items isn't wiped.

**Comment by Spice-King** [comment]
Looks like I forgot to add some fields to the template file, so Foundry was "cleaning up" for me on update. I've fixed that and 0.3.1 will be out shortly.
