### ISSUE TITLE
Request: Create Readme that includes a quick feature list and todo list

### ISSUE THREAD

**Issue by th3raid0r** [Spice-King/foundry-swnr#2]
I'd like to contribute! Could you help me out by making a Readme to help new contributors?

Just something basic to get us started:
- Title
- Description (Describe by words and images alike)
- Technologies Used
- Special Gotchas (Problems you faced, unique elements of your project)
- Technical Description (Installation, Setup, How to contribute.)

I see that you've made the choice to go with Typescript and YAML over raw Javascript and JSON. So that's pretty notable and I'm interested in how that affects my approach to contributing. It certainly differs from other notable systems like the dnd5e one used as FoundryVTT's example.

**Comment by brunocalado** [comment]
Yes, a README will be great.

**Comment by Spice-King** [comment]
Sorry @th3raid0r, I had missed the emails from GitHub until the other day when @brunocalado poked around on the SWN Discord.

I'm not the first system/module using Typescript, so nothing unique there. I opted to use it as it lets me get yelled at when I screw up. Helps prevent some dumb errors and what not.

YAML was just the result of me hating how picky JSON is and the lack of comments. As far as I'm aware, I was the first to cook that up, but I gave my gulpfile to FloRad (a Foundry Discord mod like me) for his SWADE system, so he may have committed it first to his repo. Doing it for the DB files was FloRad's idea, but I was the one to get it to work.

I'll try to do up a nice ReadMe file at some point, but it's mot much of a priority for me at the moment.

If your a Discord user, you can catch me (Spice_King#3128) on the three following (relevant) servers: [Stars Without Number Community Server](https://discord.gg/yzQ7PPX), [The Foundry](https://discordapp.com/invite/DDBZUDf), or [League of Extraordinary FoundryVTT Developers](https://discord.gg/3gWWKzk)

**Comment by Spice-King** [comment]
Right, I've made a basic README.md. Still needs some love, but I need some sleep.
