### ISSUE TITLE
Misclick on charsheet deletes items

### ISSUE THREAD

**Issue by v4mp123** [Spice-King/foundry-swnr#21]
If you accidentally click the trashcan icon while rolling a skill-roll @skilltab or doing an attack-roll @weopns-tab the skill/item is instantly deleted.
Is it possible to implement a lock/edit charsheet option (e.g. where the trashcan icon is not displayd or something like that)?

**Comment by dodgepong** [comment]
I agree, I noticed this last night when playing around with the sheet. Deleting things off your sheet should be difficult, especially skills/foci.
