### ISSUE TITLE
NPCs don't have Saving Throws

### ISSUE THREAD

**Issue by cristianmtr** [Spice-King/foundry-swnr#23]
![image](https://user-images.githubusercontent.com/8330330/111813265-401f3580-88d9-11eb-811a-56c65a116451.png)

I see it's add in the `.ts`, but not used in the sheet

**Comment by Spice-King** [comment]
This has already been solved in the sheet-rework branch. Thanks for taking the time to report it, even if I don't seem to always check GH often enough to notice it.
