### ISSUE TITLE
"Dice Pool" and "Stats" drop-down menus

### ISSUE THREAD

**Issue by aquafraternal** [Spice-King/foundry-swnr#50]
"Dice Pool" and "Stats" drop-down menus are greyed-out when you attempt to roll a skill, so you're not able to select the proper attribute or adjust the dice pool.  The default entries (2d6 and Strength) apply correctly, but cannot be modified.

**Comment by Spice-King** [comment]
Duplicate of #40. Please do double check even the closed issues for your issues in the future.

**Comment by aquafraternal** [comment]
Sorry! 🤦🏼‍♂️ I’d been surprised to not see it already reported. Thanks for the advice.
