### ISSUE TITLE
Changes to character sheet disappear

### ISSUE THREAD

**Issue by centipeda** [Spice-King/foundry-swnr#54]
I'm running Foundry 0.8.6.

Whenever I make edits to a character sheet, the changes undo themselves as soon as I click away, with the exception of the name and profile image fields:
![swn](https://user-images.githubusercontent.com/16915320/121343390-9d32f200-c8f0-11eb-8cba-3ecc533715ec.gif)

It looks like all the information that undoes itself is under the `data` attribute of the actor. Is this just a version compatibility issue?

**Comment by Leolele99** [comment]
The system isn't yet updated to foundry 0.8.X

**Comment by centipeda** [comment]
I was hoping there would end up being some forward compatibility, but it seems 0.4.2 is not functional on Foundry 0.8.6. I installed 0.7.10 and it now works properly.

Thanks for your time.

**Comment by Leolele99** [comment]
Hey sorry but how did you go about changing back to 1.7.10, especially downgrading all the addons again?

**Comment by centipeda** [comment]
Oh, sorry. I hadn't actually set anything up other than Foundry itself, so I just downloaded 0.7.10 and ran that executable instead of the 0.8.6 one. 

That might work for you, since Foundry stores data like add-ons and worlds independent of the actual installation, but I didn't have any add-ons to downgrade.
