### ISSUE TITLE
0.8.6 Compatibility

### ISSUE THREAD

**Issue by justinthejaguar** [Spice-King/foundry-swnr#55]
I was wondering if there were plans to update to the latest release version.

**Comment by Cup-of-Coffee** [comment]
In the Projects tab, you can find the card "Port to Foundry 0.8.6" in the In Progress column. 

So it seems that it's in development.

**Comment by neurorishika** [comment]
@Cup-of-Coffee I don't see the port in the Projects tab?

**Comment by Cup-of-Coffee** [comment]
![sc](https://user-images.githubusercontent.com/39238717/126658231-9bde109d-02f4-4667-982c-2346ca191bfb.png)

In addition, if you check the branches, you'll see a 0.8.x port being developed.

https://github.com/Spice-King/foundry-swnr/tree/0.8.x-port

**Comment by thadrine** [comment]
Any progress on this, or anyway I can help? 
Do not need automation, just a character sheet.

**Comment by Cup-of-Coffee** [comment]
@thadrine A new beta just got released.

https://github.com/Spice-King/foundry-swnr/releases/tag/b0.5.0
