### ISSUE TITLE
Vacc Suit Lacking Armor Stats

### ISSUE THREAD

**Issue by Cup-of-Coffee** [Spice-King/foundry-swnr#78]
The Vacc Suit provides no armor statistics. 

In SWNR, it's the same as a Armored Vacc Suit, except that it's twice as easy to puncture. 

This means it provides a AC of 13 when worn.

**Comment by Spice-King** [comment]
Vacc suits were not located in the book in the armor seciton, but other regular items.

I'll leave it in the field gear and classify it as street armor.
