### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by brunocalado** [Spice-King/foundry-swnr#82]
Hi.

Please remove the foundry vtt warning.
![image](https://user-images.githubusercontent.com/4999783/148126752-34504ad7-e9c2-484d-9752-3a922c33d72a.png)

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9"

**Comment by Spice-King** [comment]
Working as intended. Update Foundry to 0.8.9.
