### ISSUE TITLE
Editing or Adding Foci is missing?

### ISSUE THREAD

**Issue by mawburn** [Spice-King/foundry-swnr#85]
I'm not sure if I'm doing something wrong or if it's a bug. I feel like I'm doing something wrong, because this would be a pretty major bug. 

When I go to the Foci page on the character sheet, it looks like the image below. It's just blank with no clear way to add or edit Foci.

![Screen Shot 2022-08-24 at 8 40 18 AM](https://user-images.githubusercontent.com/2829924/186421973-049e6745-cba7-4912-9308-4d6ca0f0a225.jpg)

Version information:

<img width="270" alt="Screen Shot 2022-08-24 at 8 47 40 AM" src="https://user-images.githubusercontent.com/2829924/186422365-be91df18-8b8a-44ad-b827-69730c220579.png">

**Comment by mawburn** [comment]
Seems to be an issue on Combat and Equipment as well.

**Comment by Spice-King** [comment]
This is intended. Foundry's work flow uses Items with dragging and dropping to add them to Actor documents. Either from the system provided compendiums or your own custom stuff. It is intentionally made to not have buttons to just add blank Items of a given type to an Actor's sheet as to not constantly recreate Items, possibly with errors/typos.

**Comment by mawburn** [comment]
Awesome, thanks.
