### ISSUE TITLE
Duplication of Sheet Name

### ISSUE THREAD

**Issue by Cup-of-Coffee** [Spice-King/foundry-swnr#86]
Found on the Version 10 - Build 286. 

Whenever a sheet is updated in anyway, the name of the sheet in the tab duplicates, and continues to duplicate with every change. This doesn't appear to break anything else or impact any sheet functions negatively.

![Screenshot 2022-09-23 173731](https://user-images.githubusercontent.com/39238717/192060088-d3bb969a-2c24-4a93-a11d-8f22dadce137.png)

**Comment by Cup-of-Coffee** [comment]
I tested out a clean game to see if the problem persist, and they didn't. I activated all of the modules from the migrated v9 game and the bug still doesn't appear.

It might just be a bug that appears on migrated game.

**Comment by Spice-King** [comment]
Toss me a copy of the exported actor, just in case this is something I *can* take action on. Otherwise, I'm going to pin it on modules as you have at least one messing with the sheet window I can spy in that screenshot (the eye mask the top left). I've tested with both 286 and 285.
